name: NoFlyZone
main: me.clip.noflyzone.NoFlyZone
version: ${version}
authors: [extended_clip, sarhatabaot]
description: Stop players from flying in certain regions
depend:
  - WorldGuard
softdepend: [WorldEdit]
commands:
   noflyzone:
     description: NoFlyZone admin command
     aliases: [nfz]
permissions:
    noflyzone.bypass:
        description: allowed to fly anywhere
        default: op
    noflyzone.admin:
        description: allowed to use commands
        default: op